site_name: Telephoto
site_url: https://saket.github.io/telephoto/
repo_name: telephoto
repo_url: https://github.com/saket/telephoto
site_description: 'Building blocks for designing media experiences in Compose UI'
site_author: Saket Narayan
copyright: 'Copyright &copy; 2023 Saket Narayan'
remote_branch: gh-pages

theme:
  name: 'material'
  logo: assets/logo_192.png
  favicon: assets/logo_192.png
  font:
    text: 'Roboto'
    code: 'JetBrains Mono'
  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.tabs.link # Synchronize code tabs.
    - content.code.copy # For showing a copy button in code blocks.

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - toc:  # Table of contents.
      permalink: true # Anchor linking with headings.
      title: 'On this page'
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret # Underlines.
  - admonition  # Warning call-outs.

nav:
  - 'Overview': index.md
  - 'Zoomable Image':
      - 'Overview': zoomableimage/index.md
      - 'Content alignment': zoomableimage/content-alignment.md
      - 'Custom image loaders': zoomableimage/custom-image-loaders.md
      - 'Recipes': zoomableimage/recipes.md
      - 'Sub-sampling': zoomableimage/sub-sampling.md
  - 'Modifier.zoomable()':
      - 'Overview': zoomable/index.md
      - 'Recipes': zoomable/recipes.md
