[versions]
minSdk = "24"
compileSdk = "33"
kotlin = "1.8.10"
agp = "7.4.2"
compose-compiler = "1.4.4"
compose-ui = "1.4.0"
compose-ui-material3 = "1.1.0-beta01"
accompanist = "0.30.0"
androidx-appcompat = "1.6.0"
androidx-activity = "1.6.1"
androidx-ktx = "1.9.0"
testParamInjector = "1.11"
junit = "4.13.2"
truth = "1.1.3"
coil = "2.3.0"
glide = "4.15.1"
turbine = "0.12.3"
paparazzi = "1.2.0"
coroutines = "1.7.0-RC"
appyx = "1.1.1"
mavenPublish = "0.24.0"
dropshots = "0.4.0"
emulatorWtf = "0.9.5"       # https://docs.emulator.wtf/changelog/
emulatorWtf-cli = "0.9.8"   # https://docs.emulator.wtf/changelog/
okio = "3.3.0"
dokka = "1.8.10"

[libraries]
plugin-paparazzi = { module = "app.cash.paparazzi:paparazzi-gradle-plugin", version.ref = "paparazzi" }
plugin-agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
plugin-mavenPublish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "mavenPublish" }
plugin-dropshots = { module = "com.dropbox.dropshots:dropshots-gradle-plugin", version.ref = "dropshots" }
plugin-emulatorWtf = { module = "wtf.emulator:gradle-plugin", version.ref = "emulatorWtf" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-ktx" }
androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity"}

androidx-test-ktx = "androidx.test:core-ktx:1.5.0"
androidx-test-rules = "androidx.test:rules:1.5.0"
androidx-test-junit = "androidx.test.ext:junit-ktx:1.1.5"

compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-ui" }
compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose-ui" }
compose-ui-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-ui-material3" }
compose-ui-materialIcons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose-ui" }
compose-ui-test-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-ui" }
compose-ui-test-activityManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose-ui" }

accompanist-drawablePainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-test = { module = "io.coil-kt:coil-test", version.ref = "coil" }

glide-core = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

okio-core = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fakeFileSystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

junit = { module = "junit:junit", version.ref = "junit" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
testParamInjector = { module = "com.google.testparameterinjector:test-parameter-injector", version.ref = "testParamInjector" }

appyx = { module = "com.bumble.appyx:core", version.ref = "appyx" }
