name: Run tests and publish snapshot

on:
  push:
    branches: [ trunk ]
  pull_request:

jobs:
  checks:
    name: Run tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: gradle/gradle-build-action@v2

      - name: Run unit tests
        run: ./gradlew check

      - name: Run paparazzi screenshot tests
        run: ./gradlew verifyPaparazziDebug

      - name: (Fail-only) Upload paparazzi test reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-failures
          path: |
            **/build/reports/tests/*/
            **/out/failures/
            paparazzi/paparazzi-gradle-plugin/src/test/projects/**/build/reports/paparazzi/images/

      - name: Create AVD snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          profile: pixel_5
          disable-animations: false
          force-avd-creation: false
          ram-size: 4096M
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: echo "Generated AVD snapshot."

      - name: Run instrumented screenshot tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          profile: pixel_5
          disable-animations: true
          force-avd-creation: false
          ram-size: 4096M
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot-save
          emulator-build: 9475343 # https://dl.google.com/android/repository/repository2-3.xml
          script: ./gradlew connectedDebugAndroidTest --stacktrace

      - name: (Fail-only) Bundle instrumented test reports
        if: failure()
        run: find . -type d '(' -name 'reports' -o -name 'androidTest-results' ')' | zip -@ -r instrumentation-test-build-reports.zip

      - name: (Fail-only) Upload instrumented test reports
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: instrumentation-test-report
          path: instrumentation-test-build-reports.zip

  deploy-snapshot:
    name: Deploy snapshot
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.repository == 'saket/telephoto' && github.ref == 'refs/heads/trunk'
    needs: [checks]
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: gradle/gradle-build-action@v2

      - name: Publish snapshot
        run: ./gradlew clean publish --no-daemon --no-parallel --no-configuration-cache --stacktrace
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
